In [2]:
import numpy as np

In [3]:
# Buatlah Tensor di bawah ini dengan Python:
t1 = np.array ([[23, 50],
               [7, 12]])

t2 = np.array ([[57, 67],
               [99, 43]])

t3 = np.array ([[75, 21],
               [57, 12]])
               
t4 = np.array ([[87, 26],
               [18, 84]])              

In [4]:
tensor = np.array ([t1, t2, t3, t4])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [5]:
# Lakukan perkalian terhadap matrix berikut: 
a = np.array ([[23, 50, 19],
               [7, 12, 109],
               [57, 67, 98]]) # a (3,3)

b = np.array ([[17, 22, 19]]) # b (1,3)

# perkalian matriks a @ b tidak bisa karena jumlah kolom a != jumlah baris b
# perkalian matriks yang bisa b @ a karena jumlah kolom b == jumlah baris a

In [7]:
b @ a

array([[1628, 2387, 4583]])

In [9]:
# Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:
a = np.array ([[23, 50, 19],
               [7, 12, 109],
               [57, 67, 98]])
a.T # Transpose  a

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [10]:
np.linalg.det (a) # Determinan a

131344.0000000002

In [12]:
a_inv = np.linalg.inv (a)
a_inv # Inverse a

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

In [13]:
# Jika a @ a_inv maka hasilnya adalah matrix identitas
a @ a_inv

array([[1.00000000e+00, 1.90819582e-17, 1.32923186e-16],
       [7.22078647e-17, 1.00000000e+00, 5.44269491e-17],
       [6.73506390e-16, 1.97758476e-16, 1.00000000e+00]])